_target_: experiments.amplitudes.wrappers.GraphNetWrapper
particle_type: null
include_nodes: true
include_edges: true

net:
 _target_: tensorframes.nn.graphnet.TFGraphNet

 in_channels: null
 hidden_reps: "64x0n+16x1n"
 out_channels: 1
 num_edge_attr: null

 num_blocks: 3
 num_layers_mlp1: 3
 num_layers_mlp2: 0

defaults:
 - lframesnet: identity
