_target_: experiments.tagging.wrappers.TransformerWrapper
in_channels: null
out_channels: null
use_amp: false

net:
 _target_: lloca.nn.transformer.Transformer
 _partial_: true

 in_channels: null
 attn_reps: "8x0n+2x1n" # reps can be varied, but number of channels should stay fixed
 out_channels: null

 num_blocks: 10
 num_heads: 8
 mlp_factor: 4

defaults:
 - lframesnet: identity