exp_type: topxltagging
exp_name: topxl_debug

data:
 data_dir: /remote/gpu06/favaro/datasets/luigi_tagging/
 features: default
 data_config: null
 add_scalar_features: True
 train_files_range: [0, 99]
 test_files_range: [100, 119]
 val_files_range: [120, 129]

jc_params:
 num_workers: 4
 fetch_step: 0.01
 extra_selection: null
 extra-test-selection: null
 fetch_by_files: False
 in_memory: False
 not_remake_weights: False
 steps_per_epoch: null
 steps_per_epoch_val: null
 events_per_file: 1000000

evaluation:
 batchsize: 1024
 eval_set: [test]

plotting:
 roc: true
 score: true

defaults:
 - tagging
