name: Amplitudes trial experiments

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    if: github.event.label.name == 'ready for review'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: MLP + IdentityLFrames
      run: |
        python run.py -cn amplitudes model=amp_mlp save=false evaluate=false training.iterations=3

    - name: Transformer + IdentityLFrames
      run: |
        python run.py -cn amplitudes model=amp_transformer save=false evaluate=false training.iterations=3

    - name: Transformer + LearnedPolarDecompositionLFames
      run: |
        python run.py -cn amplitudes model=amp_transformer model/lframesnet=polardec save=false evaluate=false training.iterations=3

    - name: Transformer + RandomLFrames
      run: |
        python run.py -cn amplitudes model=amp_transformer model/lframesnet=randomlorentz save=false evaluate=false training.iterations=3

    - name: GraphNet (nodes+edges) + LearnedPolarDecompositionLFames
      run: |
        python run.py -cn amplitudes model=amp_graphnet model/lframesnet=polardec save=false evaluate=false training.iterations=3

    - name: GraphNet (nodes only) + LearnedPolarDecompositionLFames
      run: |
        python run.py -cn amplitudes model=amp_graphnet model/lframesnet=polardec save=false evaluate=false training.iterations=3 model.include_nodes=false

    - name: GATr + IdentityLFrames
      run: |
        python run.py -cn amplitudes model=amp_gatr save=false evaluate=false training.iterations=3

    - name: DSI + IdentityLFrames
      run: |
        python run.py -cn amplitudes model=amp_dsi save=false evaluate=false training.iterations=3
